CREATE TABLE CUSTOMER (
	CUSTOMER_ID bigint NOT NULL,
	GENDER char(1),
	FIRST_NAME varchar(64),
	LAST_NAME varchar(64),
	ADDRESS_ID bigint,
	ADDRESS_1 varchar(128),
	ADDRESS_2 varchar(128),
	ADDRESS_3 varchar(128),
	ADDRESS_STATE varchar(32),
	ADDRESS_POSTCODE varchar(32),
	CREATE_TIMESTAMP timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CREATE_EMPLOYEE_ID bigint,
	UPDATE_TIMESTAMP timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATE_EMPLOYEE_ID bigint,
	CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID)
)
;
