CREATE TABLE TEST_CSV_DATA (
    COL_ID          BIGINT NOT NULL,
    COL_DESCRIPTION VARCHAR(64),
    COL_TEXT        VARCHAR(64),
    COL_DECIMAL     DECIMAL(16,2),
    COL_FLOAT       FLOAT,
    COL_DATE        DATE,
    COL_TIME        CHAR(8),
    COL_TIMESTAMP   TIMESTAMP
)
;
